# Generated by Django 2.1.7 on 2019-03-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
